version: '3'
services:
  pyspark:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports: 
    # For local jupyter notebook access
    - 8888:8888
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    
    # Overrides default command so things don't shut down after the process ends - useful for debugging
    command: sleep infinity
    env_file:
    - ../.env
